# -*- coding: utf-8 -*-
"""Big Market Sale XGBRegressor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xtRvP8hQ3llsguYZEivTcllLMSMyhbvw

Importing Dependencies
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

"""Data Collection & Analysis"""

#loading the datset from csv file to a Panda DataFrame
big_mart_data = pd.read_csv("/content/Train.csv")

# first five rows of the dataframe

big_mart_data.head()

# numbers of datapoints and numbers of features
big_mart_data.shape

#getting some information about the dataset
big_mart_data.info()

"""Categorical Features:
*  Item_Identifier
*  Item_Fat_Content
*  Item_Type
*  Outlet_Identifier
*  Outlet_Size
*  Outlet_Loaction_Type
*  Outlet_Type










"""

# checking for missing values
big_mart_data.isnull().sum()

"""Handling the missing values
Mean -> Average value
Mode -> Most repeated vlue




"""

# mean value of item_weight column
big_mart_data['Item_Weight'].mean()

# filling the missing values i "item_weight" column with "Mean" value
big_mart_data['Item_Weight'].fillna(big_mart_data['Item_Weight'].mean() , inplace=True)

big_mart_data.isnull().sum()

"""Replacing the missing values in 'Outlet_Size' with mode"""

mode_of_Outlet_Size = big_mart_data.pivot_table(values='Outlet_Size' , columns='Outlet_Type' , aggfunc=(lambda x: x.mode()[0]))

print(mode_of_Outlet_Size)

missing_values = big_mart_data['Outlet_Size'].isnull()

print(missing_values)

big_mart_data.loc[missing_values, 'Outlet_Size'] = big_mart_data.loc[missing_values, 'Outlet_Type'].apply(lambda x: mode_of_Outlet_Size[x][0])

big_mart_data.isnull().sum()

"""Data Analysis"""

#statistical measures about the data
big_mart_data.describe()  # it gives only for numerical column

"""Numerical Features"""

sns.set()

# Item_Weight distribution

plt.figure(figsize=(6,6))
sns.distplot(big_mart_data['Item_Weight'])
plt.show()

plt.figure(figsize=(6,6))
sns.distplot(big_mart_data['Item_Visibility'])
plt.show()

plt.figure(figsize=(6,6))
sns.distplot(big_mart_data['Item_MRP'])
plt.show()

plt.figure(figsize=(6,6))
sns.distplot(big_mart_data['Item_Outlet_Sales'])
plt.show()

# Outlet_Establishment_Year column
plt.figure(figsize=(6,6))
sns.countplot(x='Outlet_Establishment_Year', data=big_mart_data)
plt.show()

"""Categorical Features"""

plt.figure(figsize=(6,6))
sns.countplot(x='Item_Fat_Content' , data=big_mart_data)
plt.plot()

plt.figure(figsize=(30,6))
sns.countplot(x='Item_Type' , data=big_mart_data)
plt.plot()

plt.figure(figsize=(6,6))
sns.countplot(x='Outlet_Size' , data=big_mart_data)
plt.show()

plt.figure(figsize=(6,6))
sns.countplot(x='Outlet_Location_Type' , data=big_mart_data)
plt.show()

plt.figure(figsize=(20,6))
sns.countplot(x='Outlet_Type' , data=big_mart_data)
plt.show()

"""Data Preprocessing"""

big_mart_data.head()

big_mart_data['Item_Fat_Content'].value_counts()

big_mart_data.replace({'Item_Fat_Content' :  {'low fat' : 'Low Fat' , 'LF' : 'Low Fat' , 'reg' : 'Regular'}}, inplace=True)

big_mart_data['Item_Fat_Content'].value_counts()

"""Label Encoding"""

encoder  = LabelEncoder()

big_mart_data['Item_Identifier']= encoder.fit_transform(big_mart_data['Item_Identifier'])
big_mart_data['Item_Fat_Content'] = encoder.fit_transform(big_mart_data['Item_Fat_Content'])
big_mart_data['Item_Type'] = encoder.fit_transform(big_mart_data['Item_Type'])
big_mart_data['Outlet_Location_Type'] = encoder.fit_transform(big_mart_data['Outlet_Location_Type'] )
big_mart_data['Outlet_Identifier'] = encoder.fit_transform(big_mart_data['Outlet_Identifier'] )
big_mart_data['Outlet_Size'] = encoder.fit_transform(big_mart_data['Outlet_Size'] )
big_mart_data['Outlet_Type'] = encoder.fit_transform(big_mart_data['Outlet_Type'] )

big_mart_data.head()

"""Splitting features and target"""

X = big_mart_data.drop(columns='Item_Outlet_Sales' , axis=1)
Y = big_mart_data['Item_Outlet_Sales']

print(X)

print(Y)

X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2 , random_state=2)

print(X.shape , X_train.shape , X_test.shape)

"""Training the machine learning model

XG Boost Regressor
"""

regressor = XGBRegressor()

regressor.fit(X_train , Y_train)

"""Evaluation"""

#predicition on training data

training_data_prediction = regressor.predict(X_train)

#R square value lies between the range of 0 to 1

r2_train = metrics.r2_score(Y_train , training_data_prediction)
print(r2_train)

testing__data_prediciton = regressor.predict(X_test)

r2_test = metrics.r2_score(Y_test , testing__data_prediciton)
print(r2_test)

"""hence the model is overfitted

"""

X1 = big_mart_data.drop(['Item_Identifier' , 'Outlet_Identifier', 'Item_Outlet_Sales'], axis=1)

model = XGBRegressor()

X1_train , X1_test , Y1_train , Y1_test = train_test_split(X1 , Y , test_size=0.2 , random_state =1)

model.fit(X1_train , Y1_train)

train_data = model.predict(X1_train)
r2_score = metrics.r2_score(Y1_train , train_data)
print(r2_score)

test_data = model.predict(X1_test)
r2_testt = metrics.r2_score(Y1_test , test_data)
print(r2_testt)