# -*- coding: utf-8 -*-
"""Breast Cancer Classification with Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mXKWh_KCpMeR7TTPOM-fTJxxHG7rtfH7

Importing the dependencies
"""

import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

"""Data Collection and Preprocessing

"""

# Loading the data from sklearn
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

print(breast_cancer_dataset)

# loading the data to panda data frame

dataframe = pd.DataFrame(breast_cancer_dataset.data, columns=breast_cancer_dataset.feature_names)

# print the first five row of the dataframe
dataframe.head()

# adding the target column to the data frame
dataframe['target'] = breast_cancer_dataset.target

#print last 5 rows of the dataframe

dataframe.head()

dataframe.shape

#getting some information about data
dataframe.info()

dataframe.isnull().sum()

dataframe.describe()

# checking the distribution of the target variable
dataframe['target'].value_counts()

dataframe.groupby('target').mean()

"""Seperating features and target"""

X = dataframe.drop(columns = 'target' , axis=1)
Y = dataframe['target']

print(Y)

"""Splittingthe data into training and testing data

"""

X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size=0.2 , random_state=2)

print(X.shape , X_train.shape , X_test.shape)

"""Model Training"""

model = LogisticRegression()

model.fit(X_train , Y_train)

"""Evaluation Prediction

Accuracy Score
"""

train_data_predict = model.predict(X_train)
train_accuracy = accuracy_score(Y_train , train_data_predict)
print(train_accuracy)

test_data_predict = model.predict(X_test)
test_accuracy = accuracy_score(Y_test , test_data_predict)
print(test_accuracy)

scaler = StandardScaler()
X1 = scaler.fit_transform(X)

model1 = LogisticRegression()

X1_train, X1_test, Y1_train, Y1_test = train_test_split(X1, Y, test_size=0.2, random_state=2)
model1.fit(X1_train, Y1_train)

train_data_predict = model1.predict(X1_train)
train_accuracy = accuracy_score(Y1_train, train_data_predict)
print(train_accuracy)  # 0.989


test_data_predict = model1.predict(X1_test)
test_accuracy = accuracy_score(Y1_test , test_data_predict)
print(test_accuracy)