# -*- coding: utf-8 -*-
"""buiding lasso regression from scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_0JY2Zec4CKsAGzJIPyQx7MFHuxsA_IP
"""

#importing the dependencies

import numpy as np

#creating a class for lasso regression
class LassoRegresion() :


  #initiating the hyperparameter
  def __init__(self , learning_rate , no_of_iteration , lamda_parameter):

    self.leraning_rate = learning_rate
    self.no_of_iteration = no_of_iteration
    self.lamda_parameter = lamda_parameter

  #fitting the dataset to the lasso regression
  def fit(self, X , Y) :

    #m -> number of data points -> numbers of rows
    #n -> number of input features -> number of columns

    self.m , self.n = X.shape ;

    self.w = np.zeros(self.n)
    self.b = 0

    self.X = X
    self.Y = Y

    for i in range (self.no_of_iteration) :
      self.update_weights()



  #function for updating the weight and the bias value
  def updateweights(self) :

    #linear equation
    Y_prediction = self.predict(self.X)

    #gradient (dw , db)
    dw = np.zeros(self.n)
    for i in range (self.n) :

      if self.w[i] > 0 :
        dw[i] = ((-2*(self.X[:,i]).dot(self.Y - Y_prediction)) + self.lambda_parameter) / self.m
      else :
        dw[i] = ((-2*(self.X[:,i]).dot(self.Y - Y_prediction)) - self.lambda_parameter) / self.m


    #gradient for bias
    db = np.sum(self.Y - Y_prediction)/self.m

    #updating the weights and bias

    self.w = self.w - self.learning_rate*dw
    self.b = self.b - self.leraning_rate*db



  #predicting the target value
  def predict(self,X) :

    return X.dot(self.w) + self.b