# -*- coding: utf-8 -*-
"""California House Price Predicition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d6qM7sOSnPorBoc2Vb2tOXtRkfcqPwjY
"""

#importing the dependencies

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn.datasets
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn import metrics

#importing the boston house price dataset

house_price_dataset = sklearn.datasets.fetch_california_housing()

print(house_price_dataset)

# Loading the datasets to a pandas dataframe
house_price_dataframe = pd.DataFrame(house_price_dataset.data , columns=house_price_dataset.feature_names)

house_price_dataframe['target'] = house_price_dataset.target ;

house_price_dataframe.head()

# checking the number of rows and columns in the data frame

house_price_dataframe.shape

#checking for the missing values

house_price_dataframe.isnull().sum()

#statistical measure of the dataset

house_price_dataframe.describe()

#understanding the correlation between various features of the dataset
# two types of correlation 1)positive correlation 2)negative correlation



correlation = house_price_dataframe.corr()

#constructing a heatmap to understand the correlation
plt.figure(figsize=(10,10))
sns.heatmap(correlation, cbar=True, square=True, fmt='.1f', annot=True, annot_kws={'size':8}, cmap='Blues')

#splitting the data and target

X = house_price_dataframe.drop(columns='target' , axis=1)
Y = house_price_dataframe['target']

print(X)

print(Y)

#splitting the data into training data and test data
X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size=0.2 , random_state=2)

print(X.shape , X_train.shape , X_test.shape)

# model training

#XGBOOST REGRESSOR

#loading the model

model = XGBRegressor()

# training the model with X_train
model.fit(X_train , Y_train)

#evaluation

#accuracy for prediction on training data

training_data_prediction = model.predict(X_train)

type(training_data_prediction)

print(training_data_prediction)

# R square error
score_1 = metrics.r2_score(Y_train , training_data_prediction)


# Mean Absolute Error
score_2 = metrics.mean_absolute_error(Y_train , training_data_prediction)

print(score_1)
print(score_2)

testing_data_predicition = model.predict(X_test)

testq_accuracy_s = metrics.r2_score(Y_test , testing_data_predicition)


test_accuracy_s2 = metrics.mean_absolute_error(Y_test , testing_data_predicition)

print(testq_accuracy_s)
print(test_accuracy_s2)