# -*- coding: utf-8 -*-
"""Deep Learning Breast Cancer Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qrONGi2Azgjmx-0GigvT27D5Z8KB9sex
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.datasets
from sklearn.model_selection import train_test_split

# loading the data from  sklearn
dataset = sklearn.datasets.load_breast_cancer()

print(dataset)

data_frame = pd.DataFrame(dataset.data , columns = dataset.feature_names)

data_frame.head()

data_frame['label'] = dataset.target

data_frame.head()

data_frame.shape

data_frame.info()

# checking for null value
data_frame.isnull().sum()

# statistical measures about the data
data_frame.describe()

# checking the distribution of target variable
data_frame['label'].value_counts()

data_frame.groupby('label').mean()

X = data_frame.drop(columns='label' , axis=1)
Y = data_frame['label']

print(X)

X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size=0.2 , random_state=2)

print(X.shape , X_train.shape , X_test.shape)

# Standardization data

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

print(X_train)

"""# Building Neural Network"""

# importing tensorflow and keras
import tensorflow as tf
tf.random.set_seed(3)
from tensorflow import keras

# setting up the layers of my neural network
model = keras.Sequential( [
    # there are 30 features
     keras.layers.Flatten(input_shape=(30,)) , # convert the data into single dimentional array
     keras.layers.Dense(20 , activation='relu') ,  # hidden
     keras.layers.Dense(2 , activation='sigmoid')    # output

 ])

# compiling the neural network

model.compile(optimizer='adam' ,
              loss='sparse_categorical_crossentropy' ,
              metrics=['accuracy'])

# training the neural network

history = model.fit(X_train , Y_train , validation_split=0.1 , epochs=10 , verbose=2)

# training the neural network

history1 = model.fit(X_train , Y_train , validation_split=0.1 , epochs=10 , verbose=1)

# training the neural network

history2 = model.fit(X_train , Y_train , validation_split=0.1 , epochs=10 , verbose=0)

"""#Visualizing  accuracy and loss"""

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')

plt.legend(['training data' , 'validaion data'] , loc = 'lower right')

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])

plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')

plt.legend(['loss' , 'validstion loss' ] , loc = 'lower right')

"""#Accuracy of the model on the test data"""

loss , accuracy = model.evaluate(X_test , Y_test)
print(accuracy)
print(loss)

print(X_test.shape)
print(X_test[0])

Y_pred = model.predict(X_test)

print(Y_pred.shape)
print(Y_pred[0])

print(Y_pred)

"""model.predict() -> gives the prediciton probability of each class for the data point"""

# converting the prediciton probability to class labels

# argmax function

my_list = [10 , 20 , 30]
index_max_value = np.argmax(my_list)
print(my_list)
print(index_max_value)

Y_pred_labels = [np.argmax(i) for i in Y_pred]

print(Y_pred_labels)

"""Building the predictive system"""

input_data = (17.99,10.38,122.8,1001,0.1184,0.2776,0.3001,0.1471,0.2419,0.07871,1.095,0.9053,8.589,153.4,0.006399,0.04904,0.05373,0.01587,0.03003,0.006193,25.38,17.33,184.6,2019,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189)

# change the input_data to numpy array
input_data_as_numpy = np.asarray(input_data)

#reshape the numpy array as we are predicitng for one data point
input_data_reshaped = input_data_as_numpy.reshape(1,-1)

# standardizing the input data
input_data_std = scaler.transform(input_data_reshaped)


prediction = model.predict(input_data_std)
print(prediction)

prediction_label = [np.argmax(prediction)]
print(prediction_label)

if(prediction_label[0] == 0) :
  print("The tumor is Malignant")
else :
  print("The tumor is Benign")