# -*- coding: utf-8 -*-
"""GridSearchCV and RandomizedSearchCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b7uLnnBAho9hQZ-e9GfzewjYvLJND9GU
"""

#hyperparameter tuning
#GridSearchCV
#RandomizedSearchCV

#importing the dependencies
import numpy as np
import pandas as pd
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

print(breast_cancer_dataset)

dataset = pd.DataFrame(breast_cancer_dataset.data , columns=breast_cancer_dataset.feature_names )

dataset.head()

dataset['label'] = breast_cancer_dataset.target

dataset.shape

dataset['label'].value_counts()

X = dataset.drop(columns='label' , axis=1)
Y = dataset['label']

print(X)

print(Y)

X = np.asarray(X)
Y = np.asarray(Y)

#GridSearchCV - this is used for determining the best  hyperparameters for our model

#loading the SVC model
model = SVC()

#HYPERPARAMETERS

parameters = {
    'kernel' : ['linear' , 'poly' , 'rbf' , 'sigmoid'] ,
    'C' : [1,5,10,20]

}

#grid search
classifier = GridSearchCV(model , parameters , cv=5)

classifier.fit(X,Y)

classifier.cv_results_

#best parameters

best_parameters = classifier.best_params_
print(best_parameters)

#higest accuracy

highest_accuracy = classifier.best_score_
print(highest_accuracy)

#loading the results to panda dataframe
result = pd.DataFrame(classifier.cv_results_)

result.head()

grid_search_result = result[['param_C' , 'param_kernel' , 'mean_test_score' ]]

print(grid_search_result)

"""#RandomizedSearchCV

"""

#loading the SVC model
model = SVC()

parameters = {
    'kernel' : ['linear' , 'poly' , 'rbf' , 'sigmoid'] ,
    'C' : [1,5,10,20]
}

classifier = RandomizedSearchCV(model , parameters , cv=5)

classifier.fit(X,Y)

classifier.cv_results_

#best parameters
best_parameter = classifier.best_params_
print(best_parameter)

#highest accuracy

highest_accuracy = classifier.best_score_
print(highest_accuracy)

#loading the result
result = pd.DataFrame(classifier.cv_results_)

print(result)

randomized_search_result = result[['param_C' , 'param_kernel' , 'mean_test_score']]

print(randomized_search_result)