# -*- coding: utf-8 -*-
"""Heart Disease Predicition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tZUNv3J5EcJebfPpQ5ozJhUIbBk57ne5
"""

#importing the dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#data collection and preprocessing

#loading the csv data to pandas dataframe
heart_data = pd.read_csv("/content/heart.csv")

heart_data.head()

heart_data.shape

# getting some info about the data

heart_data.info()

heart_data.isnull().sum()

#statistical measures about the data

heart_data.describe()

heart_data['target'].value_counts()

#splitting the features and the targets
X = heart_data.drop(columns='target' , axis=1)
Y = heart_data['target']

print(X)

print(Y)

#splitting the data into training and testing data


X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size=0.2 ,stratify=Y ,  random_state=2)

print(X.shape , X_train.shape , X_test.shape)

#model training

model = LogisticRegression()

model.fit(X_train , Y_train )

#model evaluation
#accuracy score

accuracy_training = model.predict(X_train)
acuracy_training_score = accuracy_score(accuracy_training , Y_train)

print(acuracy_training_score)

accuracy_testing = model.predict(X_test)
accuracy_testing_score = accuracy_score(accuracy_testing , Y_test)

print(accuracy_testing_score)

print(accuracy_testing)

print(Y_test)