# -*- coding: utf-8 -*-
"""Implementing  Logistic Regression from scratch .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/123uDzDtHmTkG6rJZNb0LfCXg69U3hyoz
"""

import numpy as np

class LogisticRegression() :
  #self is the reference of the instance (object)

  # declaring learning rate and number of iterations (hyper parameters )
  def __init__(self ,learning_rate , no_of_iteration ):

    self.learning_rate = learning_rate
    self.no_of_iteration = no_of_iteration

  # fit function to train the model with dataset
  def fit(self,X,Y) :

    # number of datapoints in the dataset (number of rows) --> m
    # number of input features in the dataset (number of columns)  --> n

    self.m , self.n = X.shape

    #intiating weight and bias value

    self.w = np.zeros(self.n) ;
    self.b = 0

    self.X = X
    self.Y = Y

    for i in range (self.no_of_iteration) :
     self.update_weights()


  def update_weights(self) :

    #Y_cap formula (sigmoid formula)

    Y_hat = 1/(1+ np.exp(-(self.X.dot(self.w) + self.b) ))

    #derivative

    dw = (1/self.m )*np.dot(self.X.T , (Y_hat - self.Y))
    db = (1/self.m)*np.sum(Y_hat - self.Y)

    #updating the weights and bias using the gradient descent
    self.w = self.w - self.learning_rate*dw
    self.b = self.b - self.learning_rate*db


  #Sigmoid Equation and Descion Boundary
  def predict(self , X) :
      Y_pred = 1/(1+ np.exp(-(X.dot(self.w) + self.b) ))
      Y_pred = np.where(Y_pred > 0.5 , 1 , 0)
      return Y_pred

#importing the dependencies
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

dataset = pd.read_csv("/content/diabetes (1).csv")

dataset.head()

dataset.tail()

dataset.shape

dataset.isnull().sum()

dataset['Outcome'].value_counts()
# 1 -> diabetic
# 0 -> non-diabetic

dataset.describe()

dataset.info()

dataset.groupby('Outcome').mean()

#seperating the feature and the target

features = dataset.drop(columns = 'Outcome' , axis = 1)
target = dataset['Outcome']

print(features)

print(target)

scaler = StandardScaler()

scaler.fit(features)
features = scaler.transform(features)

print(features)

X_train , X_test , Y_train , Y_test = train_test_split(features , target , test_size = 0.2 , random_state = 2 )

print(features.shape , X_train.shape , X_test.shape)

classifier = LogisticRegression(learning_rate=0.01 , no_of_iteration = 1000)

classifier.fit(X_train,Y_train)

X_train_prediction = classifier.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction , Y_train)

print(training_data_accuracy)

X_test_prediction = classifier.predict(X_test)
testing_data_accuracy = accuracy_score(X_test_prediction , Y_test)

print(testing_data_accuracy)