# -*- coding: utf-8 -*-
"""Implementing the linear regression made from scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yeKG37i3N3a9wqJ7kxl1NbRU3JZGechE
"""

import numpy as np

class Linear_Regression() :
  #only fit and predic function will be used outside the class the init and update weights will be used within the class


    def __init__(self, learning_rate , no_of_iteration):
      self.learning_rate = learning_rate
      self.no_of_iteration = no_of_iteration



    def fit(self,X,Y) :
      #number of training (number of datapoints) examples & number of features
      self.m , self.n = X.shape #numbers of rows and numbers of columns , m represent the row and n represent the column
      self.w =  np.zeros(self.n)
      self.b = 0
      self.X = X
      self.Y = Y

      # implementing gradient descent
      for i in range (self.no_of_iteration) :
        self.update_weights()






    def update_weights(self,) :
      Y_prediction = self.predict(self.X)

      # calculating gradient
      dw = -(2*(self.X.T).dot(self.Y - Y_prediction))/self.m
      db = -2*np.sum(self.Y - Y_prediction)/self.m

      #updating the weights
      self.w = self.w - self.learning_rate*dw
      self.b = self.b - self.learning_rate * db



    def predict(self,X) :
      return X.dot(self.w) + self.b

#using linear regression for prediciton

import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

#data preprocessing

#loading the data from the csv file to the dataframe
salary_data = pd.read_csv("/content/salary_data.csv")

#printing the first 5 columns of the dataset
salary_data.head()

#printing the last 5 row of the dataset
salary_data.tail()

#number of row and columns in the dataframe
salary_data.shape

#checking if there is any missing value

salary_data.isnull().sum()

X = salary_data.iloc[:,:-1].values
Y = salary_data['Salary']

print(X)

#splitting the dataset into train and test data

X_train , X_test , Y_train , Y_test = train_test_split(X,Y,test_size=0.33 , random_state = 2)

#training the linear regression model
model = Linear_Regression(learning_rate=0.02 , no_of_iteration=1000)
model.fit(X_train , Y_train )

# printing the parameter value (weight and bias)

print('weight = ' , model.w[0])
print('bias =  ' , model.b)

# salary = 9621(experience) + 25441

#predict the salary value for the test data

test_data_prediction = model.predict(X_test)

print(test_data_prediction)

#visualizing the predicted value and the actual value

plt.scatter(X_test , Y_test , color='red')
plt.plot(X_test , test_data_prediction , color='blue') #value predicited by our model
plt.xlabel('Work Experience')
plt.ylabel('Salary')
plt.title('Salary vs Experience')
plt.show()

from sklearn.metrics import mean_squared_error

mean_squared = mean_squared_error(Y_test , test_data_prediction)
print(mean_squared)

rmse = np.sqrt(mean_squared)
print(rmse)

from sklearn.metrics import r2_score
r2 = r2_score(Y_test , test_data_prediction)
print(r2)