# -*- coding: utf-8 -*-
"""implementing kfold cross validation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTDA18ETW9CmZNWn3jwcobO6m12tZJEC
"""

#importing the dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score

#importing the models
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

dataset = pd.read_csv("/content/heart_disease_data.csv")

dataset.head()

dataset.shape

dataset.isnull().sum()

dataset.value_counts('target')
#1 -> defective heart
#0 -> healthy heart

#splitting the datset into features and target
X = dataset.drop(columns='target' , axis=1)
Y = dataset['target']

print(X)

print(Y)

#train test split

X_train , X_test , Y_train , Y_test = train_test_split(X,Y, test_size=0.2, stratify=Y , random_state=3)

print(X.shape , X_train.shape , X_test.shape)

#comparing the performance of the model


#list of models

models = [LogisticRegression(max_iter=1000) , SVC(kernel='linear') , KNeighborsClassifier() , RandomForestClassifier()]

def compare_models_train_test_split() :
  for model in models :

    #training the model
    model.fit(X_train,Y_train)
    #evaluating the model
    test_data_predicition = model.predict(X_test)
    accuracy = accuracy_score(Y_test,test_data_predicition)
    print("Accuracy score of the model ",model," = " , accuracy)

compare_models_train_test_split()

#Cross validation

cv_score_lr = cross_val_score(LogisticRegression(max_iter=1000) , X , Y ,cv=5)
print(cv_score_lr)
mean_accuracy_lr = sum(cv_score_lr)/len(cv_score_lr)
mean_accuracy_lr = mean_accuracy_lr*100
mean_accuracy_lr = round(mean_accuracy_lr , 2)
print(mean_accuracy_lr)

#cross validation for support vector machine
cv_score_svc = cross_val_score(SVC(kernel='linear') , X , Y , cv=5)
print(cv_score_svc)
mean_accuracy_svc = sum(cv_score_svc)/len(cv_score_svc)
mean_accuracy_svc = mean_accuracy_svc * 100
mean_accuracy_svc = round(mean_accuracy_svc , 2)
print(mean_accuracy_svc)

#creating the function to compare the models

models = [LogisticRegression(max_iter=1000) , SVC(kernel='linear') , KNeighborsClassifier() , RandomForestClassifier()]

def compare_model_cross_validation() :
  for model in models :
    cv_score = cross_val_score(model,X,Y,cv=5)
    mean_accuracy = sum(cv_score)/len(cv_score)
    mean_accuracy = mean_accuracy*100
    mean_accuracy = round(mean_accuracy , 2)
    print('Cross Validation accuracies for  ', model , ' = ' , cv_score)
    print('Accuracy % of the model ',model , mean_accuracy)
    print('------------------------------------------------')

compare_model_cross_validation()