# -*- coding: utf-8 -*-
"""Loan Status Prediction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LKxDk3NX4fxuG8m-kWEf-oZ0VIWVmdxd
"""

# importing the dependencies

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score

# data collection and preprocessing

#loading dataset to pandas dataframe
loan_dataset = pd.read_csv("/content/loan_dataset.csv")

# printing the first 5 rows of the dataframe

loan_dataset.head()

# numbers of rows and columns

loan_dataset.shape

# statistical measures

loan_dataset.describe()

# numbers of missing values

loan_dataset.isnull().sum()

# dropping the missing values

loan_dataset = loan_dataset.dropna()

loan_dataset.isnull().sum()

loan_dataset.shape

from sklearn.preprocessing import LabelEncoder

#label encoding
encoder = LabelEncoder()

loan_dataset['Gender'] = encoder.fit_transform(loan_dataset['Gender'])

loan_dataset.head()

loan_dataset['Education'].value_counts()

loan_dataset.replace({"Education" : {"Graduate" : 0 , "Not Graduate" : 1} } , inplace=True)

loan_dataset.head()

loan_dataset['Dependents'].value_counts()

loan_dataset.replace({"Dependents" : {'3+' : '4'} }  , inplace=True)

loan_dataset['Dependents'].value_counts()

loan_dataset.head()

#Data Visulaization

#education and loan status

sns.countplot(x='Education' , hue='Loan_Status' , data=loan_dataset)

sns.countplot(x='Married' , hue='Loan_Status' , data=loan_dataset)

sns.countplot(x='Gender' , hue='Loan_Status' , data=loan_dataset)

loan_dataset.head()

loan_dataset['Married'] = encoder.fit_transform(loan_dataset['Married'])
loan_dataset['Self_Employed'] = encoder.fit_transform(loan_dataset['Self_Employed'])
loan_dataset['Property_Area'] = encoder.fit_transform(loan_dataset['Property_Area'])
loan_dataset['Loan_Status'] = encoder.fit_transform(loan_dataset['Loan_Status'])

loan_dataset.head()

loan_dataset.shape

#seperating the data and label

X = loan_dataset.drop(columns=['Loan_ID' , 'Loan_Status'] , axis=1)
Y = loan_dataset['Loan_Status']

print(X)
print(Y)

#splitting the dataset into train and test


X_train , X_test , Y_train , Y_test = train_test_split(X , Y , test_size=0.1 ,stratify=Y ,  random_state = 2)

print(X.shape , X_train.shape , X_test.shape)

#traing the model

model = svm.SVC(kernel='linear')

model.fit(X_train , Y_train)

#model evaluation


train_predict = model.predict(X_train)
accuracy_train = accuracy_score(train_predict , Y_train)
print(accuracy_train)

test_predict = model.predict(X_test)
accuracy_test = accuracy_score(test_predict , Y_test)
print(accuracy_test)