# -*- coding: utf-8 -*-
"""Making Logistic Regression from scratch .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18OqAGmJtP1FUw7nIyqdZaN-h3wPFGHq1
"""

#importing the dependencies

import numpy as np

class LogisticRegression() :

  # declaring learning rate and number of iterations (hyper parameters )
  def __init__(self ,learning_rate , no_of_iteration ):

    self.learning_rate = learning_rate
    self.no_of_iteration = no_of_iteration

  # fit function to train the model with dataset
  def fit(self,X,Y) :

    # number of datapoints in the dataset (number of rows) --> m
    # number of input features in the dataset (number of columns)  --> n

    self.m , self.n = X.shape

    #intiating weight and bias value

    self.w = np.zeros(self.n) ;
    self.b = 0

    self.X = X
    self.Y = Y

    for i in range (self.no_of_iteration) :
     self.update_weights()


  def update_weights(self) :

    #Y_cap formula (sigmoid formula)

    Y_hat = 1/(1+ np.exp(-(self.X.dot(self.w) + self.b) ))

    #derivative

    dw = (1/self.m )*np.dot(self.X.T , (Y_hat - self.Y))
    db = (1/self.m)*np.sum(Y_hat - self.Y)

    #updating the weights and bias using the gradient descent
    self.w = self.w - self.learning_rate*dw
    self.b = self.b - self.learning_rate*db


  #Sigmoid Equation and Descion Boundary
  def predict(self , X) :
      Y_pred = 1/(1+ np.exp(-(X.dot(self.w) + self.b) ))
      Y_pred = np.where(Y_pred > 0.5 , 1 , 0)
      return Y_pred