# -*- coding: utf-8 -*-
"""Matrix Operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IsPGJSxL9CnT-eomfs7Rsz_PgwCs8b2c
"""

#Addition
#Substraction
#Scalar Multiplication
#Mulyiplication

#importing numpy
import numpy as np
#Matrix Addition
#Creating 2 matrices

a = np.array([[2,3] , [4,5]])

b = np.array([[6,7] , [8,9]])

print(a)
print(b)

a.shape

b.shape

#adding 2 matrices

sum = a + b
print(sum)

#creating 2 matrices with random values

matrix_1 = np.random.randint(10 , size=(3,3))
matrix_2 = np.random.randint(20 , size=(3,3))

print(matrix_1)
print(matrix_2)

sum = np.add(matrix_1 , matrix_2)
print(sum)

a = np.array([[2,3] , [4,5]])

b = np.array([[6,7] , [8,9]])

diff = a - b
print(a)
print(b)
print(diff)

matrix_1 = np.random.randint(10 , size=(3,3))
matrix_2 = np.random.randint(20 , size=(3,3))
print(matrix_1)
print(matrix_2)

diff = np.subtract(matrix_1,matrix_2)

print(diff)

#multiplying a matrix by a scalar value
x = 5
y = np.random.randint(10, size=(4,4))
print(y)

product = np.multiply(x,y)
print(product)

print(x*y)

#multiplying 2 matrix
matrix_1 = np.random.randint(5 , size=(3,3))
matrix_2 = np.random.randint(5 , size=(3,4))

print(matrix_1)
print(matrix_2)

product = np.dot(matrix_1,matrix_2)
print(product)

