# -*- coding: utf-8 -*-
"""Numerical Data Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLZQrF9OAqkiUXKi9KLm7cHuhB3b22-k
"""

#importing the dependencies
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

#loading the dataset to the pandas dataframe . the dataset is in cvs form and pandas convert it into a table dataframe
dataset = pd.read_csv("/content/diabetes (1).csv")

dataset.head()

#so there are 768 rows and 9 columns
dataset.shape

#checking for data imbalance it is not imbalanced
dataset['Outcome'].value_counts()

#checking for any missing values
dataset.isnull().sum()

#seperating the features and the target columns
X = dataset.drop(columns = 'Outcome' , axis = 1)
Y = dataset['Outcome']

print(X)
print(Y)
print(X.shape)
print(Y.shape)

#performing standardization
scaler = StandardScaler()
X= scaler.fit_transform(X)

print(X)
print(X.shape)

#splitting the dataset into testing and training
X_train , X_test ,  Y_train , Y_test  = train_test_split(X , Y , test_size = 0.2 , random_state = 2 )

print( X.shape , X_train.shape , X_test.shape)

print( Y.shape , Y_train.shape , Y_test.shape)