# -*- coding: utf-8 -*-
"""pytorch fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GhjtU3NRWZiTsruAfn9UW3pKWqjQsS6E
"""

import torch
print(torch.__version__)

!nvidia-smi

"""#Introduction to Tensors

Creating Tensors
"""

#scaler

scaler = torch.tensor(7)
scaler

scaler.ndim

# Get tensor back as Python int
scaler.item()

# vector

vector = torch.tensor([7,7])
vector

vector.ndim

vector.shape

# Matrix
MATRIX = torch.tensor([[7,8] ,
                       [4,5]])
MATRIX

MATRIX.ndim

MATRIX[0]

MATRIX[1]

MATRIX.shape

# TENSOR
TENSOR = torch.tensor([[[1 , 2 , 3] ,
                        [4 , 5 ,6 ] ,
                        [3 , 6 , 7]]])
TENSOR

TENSOR.ndim

TENSOR.shape

TENSOR[0]

TENSOR1 = torch.tensor([[[1,2] ,
                         [3,4] ,
                         [5,6]], [
                             [3,4] ,
                             [5,6] ,
                             [7,8]
                         ]])
TENSOR1

TENSOR1.ndim

TENSOR1.shape

TENSOR2 = torch.tensor([[[[1,2] ,
                         [3,4]] ,
                         [[5,6] ,
                         [9,10]]] ,
                        [[[11,12] ,
                         [15,16] ],
                         [[17,18] ,
                          [19,20]]] ])

TENSOR2

TENSOR2.ndim

TENSOR2.shape

"""#Random Tensor

Why random tensor
Random tensor are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers
"""

# creating a random tensor of size(3,4)

random_tensor = torch.rand(3,4)
random_tensor

random_tensor.ndim

t1 = torch.rand(2,4,10)
t1

# Create a random tensor with similar shape to an image tensor

random_image_size_tensor = torch.rand(size=(224,224,3)) #height , width , colour channels (R , G , B)

random_image_size_tensor.shape , random_image_size_tensor.ndim

"""#Zeros and ones"""

# creating a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

# creating a tensor of all ones
ones = torch.ones(size=(3,4))
ones

ones.dtype

"""#Creating a range of tensors and tensors-like"""

# use torch.range()
torch.range(0,10)

torch.arange(0,10)

#creating tensor like
one_ten = torch.arange(1,11,1)
ten_zeros = torch.zeros_like(one_ten)
ten_zeros

ten_zero = one_ten
ten_zero