# -*- coding: utf-8 -*-
"""Simplest ANN .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DA0EP5M_8qVnujZVdSZSlj9MzlXjozQ9
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder , StandardScaler
from sklearn.linear_model import Perceptron # preceptron single layered neural network used for simple linear task such as binary classification
from sklearn.metrics import accuracy_score , classification_report , confusion_matrix

import tensorflow as tf
# lets you build a neural network layer by layer in a linear fashion
from tensorflow.keras.models import Sequential
# fully connected layer (every neurons connects to every neuron in the next layers)
from tensorflow.keras.layers import Dense
# Randomly drops some neurons during training to prevent overfitting
from tensorflow.keras.layers import Dropout
# Converts class labels (like 0 , 1 , 2) into one_hot encoded format (eg [1,0,0][0,0,1])
from tensorflow.keras.utils import to_categorical

df = pd.read_csv('/content/iris.csv')

df.head()

df['variety'].value_counts()

df.info()

df.shape

sns.pairplot(df , hue='variety')

X = df.drop(columns='variety' , axis=1)
Y = df['variety']

encoder = LabelEncoder()
y_int = encoder.fit_transform(Y)

y_int

X_train , X_test , Y_train , Y_test = train_test_split(X,y_int, test_size=0.2 , stratify=y_int, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.fit_transform(X_test)

per = Perceptron(max_iter = 1000 , random_state = 42)
per.fit(X_train , Y_train)

y_pred_precep = per.predict(X_test)

accuracy_score(Y_test , y_pred_precep)

print(classification_report(Y_test , y_pred_precep))

"""#ANN"""

Y_train = to_categorical(Y_train , num_classes=3)
Y_test = to_categorical(Y_test , num_classes=3)

Y_train

model = Sequential([
    Dense(16,input_dim=4 , activation='relu') ,
    Dense(8 , activation='relu') ,
    Dense(3 , activation='softmax')
])

model.compile(optimizer='adam' , loss='categorical_crossentropy' , metrics = ['accuracy'])

Y_train.shape

X_train.shape

history = model.fit(X_train , Y_train ,
                    epochs = 100 ,
                   batch_size = 8 ,
                   validation_split = 0.2 ,
                   verbose=1 )

loss , acc = model.evaluate (X_test , Y_test , verbose =1)
print(acc)

plt.figure(figsize = (10,4))
plt.plot(history.history['accuracy'] , label="train Acc")