# -*- coding: utf-8 -*-
"""Spam Mail or Not Detetcion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17GXimG4n7FKsTuGXLasPuobhkuSXEe1r
"""

#importing the dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

#data collection and data preprocessing
data = pd.read_csv("/content/mail_data.csv")

print(data)

data.head()

data.shape

mail_data = data.where((pd.notnull(data)),'')

#printing the first five row of data frame
mail_data.head()

#label encoding spam-0 ham-1
mail_data.loc[mail_data['Category']=='spam' , 'Category' , ] = 0
mail_data.loc[mail_data['Category']== 'ham' , 'Category' ,] = 1

#seperating the data as text and data
X = mail_data['Message']
Y = mail_data['Category']

print(X)
print(Y)

#splitting the array between the train and test split
X_train , X_test , Y_train , Y_test = train_test_split(X,Y, test_size=0.2 , random_state=3)

print(X.shape , X_test.shape , X_train.shape)

#converting the text data to numerical
#this is know as feature extraction
#transform the text data to the feature vectors that can be used as input to the logistic regression

feature_extraction = TfidfVectorizer(min_df=1 , stop_words='english' , lowercase=True)


X_train_features =  feature_extraction.fit_transform(X_train)
X_test_features = feature_extraction.transform(X_test)

#convert Y_train and Y_test values as integers
Y_train = Y_train.astype('int')
Y_test = Y_test.astype('int')

print(X_train_features)

#training the machine learning model
#logistic regression
model = LogisticRegression()

#training the logistic regression model
model.fit(X_train_features , Y_train)

#evaluating the trained model
prediction_training = model.predict(X_train_features)
accuracy_training = accuracy_score(Y_train , prediction_training)
print(accuracy_training)

prediction_testing = model.predict(X_test_features)
accuracy_testing = accuracy_score(Y_test , prediction_testing)
print(accuracy_testing)