# -*- coding: utf-8 -*-
"""Tensor Datatype.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jdxMegWAYAOJwpYJ1XsSBZgIKsBaL3C8
"""

import torch

"""Tensor datatypes is one of the 3 big errors you will run into with Pytorch and Deep learning :
1. Tensors not right Datatype
2. Tensors not right shape
3. Tensors not on right device
"""

# float 32 tensor

float_32_tensor = torch.tensor([3.0 , 6.0 , 9.0] ,
                               dtype=None ,
                               device = None , # what device is your tensor on cpu or cuda
                               requires_grad = False # whether or not to track gradients with this tensor operation
                               )

float_32_tensor

float_32_tensor.dtype

float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

float_16_tensor * float_32_tensor

l = float_16_tensor
l

float_32 = float_16_tensor
float_32

int_32_tensor =  torch.tensor([3,6,9] ,
                              dtype = torch.int32)
int_32_tensor

float_32_tensor * int_32_tensor

"""# Getting information
1. Tensors not right Datatype  = to get datatype from a tensor can use tensor.dtype
2. Tensors not right shape  = to get shape from a tensor , can use tensor.shape
3. Tensors not on right device = to get device from a tensro , can use tensor.device
"""

# create a tensor
some_tensor = torch.rand(3,4)
some_tensor

# size is function shape is attribute

# find out details about some tensor

print(some_tensor)
print("DataType of the tensor :  " , some_tensor.dtype)
print("\nShape of tensor : " , some_tensor.shape)
print("\nDevice tensor is on : " , some_tensor.device)

l = torch.tensor([3,4,5] ,
                 dtype = torch.int32)

print(l.shape)

print(l.dtype)

l = l.type(torch.int64)

print(l.dtype)

print(l.device)

"""###Manipulating Tensors

Tensor Operation include :
1. Addition
2. Substraction
3. Multiplication (element wie)
4. Division
5. Matrix Multiplication
"""

# addition

# create a tensor

tensor = torch.tensor([1,2,3])

tensor + 100

# Multiply tensor by 10
tensor = tensor * 10

tensor

# subtract 10
tensor - 10

# try out pytorch inbuilt function
torch.mul(tensor , 10)

torch.add(tensor , 6)

"""### Matrix Multiplication

Two main ways to performing multiplication in neural network and deep learning

1. Element-wise multiplication
2. Matrix multiplication  (most common operation we will find in the neural network )


there are two main rules that performing matrix multiplication needs to satisfy 🇰
1. the inner dimensions must match
(3,2) @ (2,3) -> this would work
2. The resulting matrix has the shape of the outer dimension
"""

# element wise

tensor = torch.tensor([1,2,3])

tensor

tensor * tensor

# Matrix Multiplication
torch.matmul(tensor , tensor)

len(tensor)

# Commented out IPython magic to ensure Python compatibility.
# # Matrix multiplication by hand
# %%time
# value = 0
# 
# for i in range (len(tensor)) :
#   value += tensor[i] * tensor[i]
# print(value)

# Commented out IPython magic to ensure Python compatibility.
# %%time
# torch.matmul(tensor , tensor)

"""On of the most common errors in deep learning shape errors"""

# shapes for matrix multiplication

tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]] )

tensor_A.shape
tensor_B.shape

"""To fix our tensor shape issue we can manipulate the shape of one of our tensor using transpose"""

tensor_B

tensor_B.T , tensor_B.T.shape

torch.mm(tensor_A , tensor_B.T)

torch.mm(tensor_A , tensor_B.T).shape