# -*- coding: utf-8 -*-
"""vector operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LwtGoQswkT43CpaWP9JkIgifSPV8W3D9
"""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set()

#plotting a vector
plt.quiver(0,0,4,5)
plt.show()

plt.quiver(0,0,4,5,scale_units='xy' , angles='xy' , scale=1)
plt.xlim(-8,8)
plt.ylim(-8,8)

plt.quiver(0,0,4,5,scale_units='xy',angles='xy',scale=1 , color='b' )
plt.xlim(-8,8)
plt.ylim(-8,8)

plt.quiver(0,0,4,5,scale_units='xy',angles='xy', scale=1 , color='b')
plt.quiver(0,0,-3,-6,scale_units='xy' , angles='xy' , scale=1 , color='g')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

#Addition of 2 vectors
vector_1 = np.asarray([0,0,2,3])

vector_2 = np.asarray([0,0,3,-2])

sum1 = vector_1 + vector_2
print(sum1)

plt.quiver(0,0,2,3 , scale_units='xy' , angles='xy' , scale=1 , color='b')
plt.quiver(0,0,3,-2 ,scale_units='xy' , angles='xy' , scale=1 , color='g')
plt.quiver(0,0,5,1,scale_units='xy' , angles='xy' , scale=1 , color='r')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

#substraction of 2 vector

vector_1 = np.asarray([0,0,2,3])
vector_2 = np.asarray([0,0,3,-2])

diff = vector_1 - vector_2
print(diff)

plt.quiver(0,0,2,3 , scale_units='xy' , angles='xy' , scale=1 , color = 'b')
plt.quiver(0,0,3,-2 , scale_units='xy' , angles='xy' , scale=1 , color='g')
plt.quiver(0,0,-1,5,scale_units='xy' , angles='xy' , scale=1 , color='r')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

#multiplying the vector with scalar
vector_1 = np.asarray([0,0,2,3])

vector_2 = 2*vector_1
print(vector_2)

plt.quiver(0,0,2,3,scale_units='xy' , angles='xy' , scale=1 , color='b')
plt.quiver(0,0,4,6,scale_units='xy' , angles='xy' , scale=1 , color='r')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

vector_1 = np.asarray([0,0,2,3])

vector_2 = -0.5*vector_1
print(vector_2)

plt.quiver(0,0,2,3,scale_units='xy' , angles='xy' , scale=1 , color='b')
plt.quiver(0,0,-1,-1.5,scale_units='xy' , angles='xy' , scale=1 , color='r')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

plt.quiver(0,0,2,3 , scale=2, color='b')
plt.xlim(-8,8)
plt.ylim(-8,8)
plt.show()

#dot product , cross product and projection
#dot product of 2 vector

a = np.array([2,3])
b = np.array([4,4])

a_dot_b = np.dot(a,b)
print(a_dot_b)

c = np.array([40,20,35])
d = np.array([53,24,68])

c_dot_d = np.dot(c,d)
print(c_dot_d)

# cross product -> result of cross product is vector

a = np.array([2,3])

b = np.array([4,4])

a_cross_b = np.cross(a,b)
print(a_cross_b)

c = np.array([5 , 10 , 20])

d = np.array([18 , 32 , 50])

product = np.cross(c,d)
print(product)

#projection of 'a' vector on 'v' vector
a = np.array([2,5])

v = np.array([8,-6])

#magnitude of v vector
mag_v = np.sqrt(sum(v**2))

projection = (np.dot(a,v)/mag_v**2) * v

print("Projection of a vector : ",projection)