# -*- coding: utf-8 -*-
"""Working with matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X-qDDS1z1Z8-jXBjddHlrRRemps1vQN2
"""

import numpy as np

# creating a matrix using numpy
matrix_1 = np.array([[2,3] , [6,7]])
print(matrix_1)

#attribute
matrix_1.shape

matrix_2 = np.array([[10 , 35 , 45] , [50 , 64 , 80] , [20 , 15 , 90]])
print(matrix_2)

matrix_2.shape

#creating matrices with randome values
random_matrix = np.random.rand(3,3)
print(random_matrix)

#creating matrix with random integer
random_integer_matrix = np.random.randint(100 , size = (4,5))
print(random_integer_matrix)

#creating matrix with all the values as 1

matrix_3 = np.ones((2,3))
print(matrix_3)

matrix_4 = np.ones((2,3) , dtype=int)
print(matrix_4)

#null matrix or zero matrix

null_matrix = np.zeros((4,4))
print(null_matrix)

#identity matrix
identity_matrix = np.eye(3,3)
print(identity_matrix)

#transpose of matrix
a = np.random.randint(100 , size=(4,5))
print(a)

transpose_a = np.transpose(a)
print(transpose_a)

a.T